export const SET_INITIAL_STATE = 'SET_INITIAL_STATE';
export const SET_CREATION_STATE = 'SET_CREATION_STATE';
export const SET_MAIN_STATE = 'SET_MAIN_STATE';
export const SET_PRIVATE_KEY = 'SET_PRIVATE_KEY';
export const SET_PUBLIC_KEY = 'SET_PUBLIC_KEY';
export const SET_ACCOUNT_BALANCE = 'SET_ACCOUNT_BALANCE';
export const SET_SIGN_TRANSACTION_FUNCTION = 'SET_SIGN_TRANSACTION_FUNCTION';
